# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 1
updates:
  # Enable version updates for npm
  - package-ecosystem: "rust"
    directory: "/"
    schedule:
      interval: "daily"
